/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.lez4_oo_extends;

import myClasses.Commesso;
import myClasses.Cliente;
import java.time.LocalDate;
import java.util.ArrayList;

/**
 *
 * @author tss
 */
public class GestShop extends javax.swing.JFrame {
    final int MAXCODE =5;
    Commesso myCommesso;
    Cliente myCliente;
    ArrayList<Cliente> elencoClienti;

    /**
     * Creates new form GestShop
     */
    public GestShop() {
        initComponents();
        elencoClienti = new ArrayList<>();
    }

    public int generateCode(int maxvalue) {
        double ris = 0;
        double rand = Math.random();
        ris = rand * maxvalue;
        return (int) ris;
    }

    private boolean checkCodNotInElenco(int cod) {
        
        for (Cliente e:elencoClienti ){
            if (e.getCodcliente()==cod) {
                System.out.println("codice gia' usato:" +cod);
                return false;
            }
            
        }
        return true;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tCognome = new javax.swing.JTextField();
        tNome = new javax.swing.JTextField();
        tLuogonascita = new javax.swing.JTextField();
        bNewCommesso = new javax.swing.JButton();
        bNewCliente = new javax.swing.JButton();
        lCliente = new javax.swing.JLabel();
        lCommesso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bNewCommesso.setText("nuovo commesso");
        bNewCommesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNewCommessoActionPerformed(evt);
            }
        });

        bNewCliente.setText("nuovo cliente");
        bNewCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNewClienteActionPerformed(evt);
            }
        });

        lCliente.setText("---");

        lCommesso.setText("---");

        jLabel1.setText("ins cognome");

        jLabel2.setText("ins nome");

        jLabel3.setText("ins luogo nascita");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tLuogonascita, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tCognome, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bNewCommesso, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(bNewCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lCommesso, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(538, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tLuogonascita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNewCommesso)
                    .addComponent(lCommesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNewCliente)
                    .addComponent(lCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(76, 76, 76)
                    .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(359, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNewCommessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNewCommessoActionPerformed
        // TODO add your handling code here:
        String cog = tCognome.getText();
        String nom = tNome.getText();
        String luo = tLuogonascita.getText();
        //recuperate info da interfaccia
        LocalDate data = LocalDate.now();
        int matr = 1;
        //create info supplementari
        Commesso com = new Commesso(cog, nom, luo, data, matr);
        //creata istanza di oggetto commesso

        myCommesso = com;
        lCommesso.setText(myCommesso.getInfo());

        //assegnato il nuovo commesso al commesso ufficiale del negozio
    }//GEN-LAST:event_bNewCommessoActionPerformed

    private void bNewClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNewClienteActionPerformed
        // TODO add your handling code here:
        String cog = tCognome.getText();
        String nom = tNome.getText();
        String luo = tLuogonascita.getText();
        //recuperate info da interfaccia
        LocalDate data = LocalDate.now();
        int cod = 1;
        boolean ok = false;
        while (ok==false) {
            cod = generateCode(MAXCODE);
            ok = checkCodNotInElenco(cod);
        }
        //create info supplementari
        Cliente cli = new Cliente(cog, nom, luo, data, cod);
        //creata istanza di oggetto commesso
        elencoClienti.add(cli);
        myCliente = cli;
        lCliente.setText(myCliente.getInfo());

        //assegnato il nuovo commesso al commesso ufficiale del negozio

    }//GEN-LAST:event_bNewClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestShop().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bNewCliente;
    private javax.swing.JButton bNewCommesso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lCliente;
    private javax.swing.JLabel lCommesso;
    private javax.swing.JTextField tCognome;
    private javax.swing.JTextField tLuogonascita;
    private javax.swing.JTextField tNome;
    // End of variables declaration//GEN-END:variables

}
